const data={
    products: [
        {
         id: "1",
        name:'Gucci Leather Bags',
        category:'luggages',
        image:'/images/p1.jpg',
        price: 5999,
        countInStock: 20,
        brand: 'Gucci',
        ratings: 4.2,
        numReviews:10,
        description: 'High quality product',
        },
        {
            id: "2",
            name:'Head Phones',
            category:'electronics',
            image:'/images/p2.jpg',
            price: 15759,
            countInStock: 10,
            brand: 'jbl',
            ratings: 4.2,
            numReviews:10,
            description: 'High quality product',
            },
            {
                id: "3",
                name:'Travel bag combo',
                category:'luggages',
                image:'/images/p3.jpg',
                price: 8999,
                countInStock: 20,
                brand: 'Supreme',
                ratings: 4.2,
                numReviews:10,
                description: 'High quality product',
                },
                {
                    id: "4",
                    name:'Nike shoes',
                    category:'life styles',
                    image:'/images/p4.jpg',
                    price: 6599,
                    countInStock: 30,
                    brand: 'Nike',
                    ratings: 4.9,
                    numReviews:10,
                    description: 'High quality product',
                    },
                    {
                        id: "5",
                        name:'Swaroeski pemdant',
                        category:'life styles',
                        image:'/images/p5.jpg',
                        price: 7589,
                        countInStock: 40,
                        brand: 'neckles',
                        ratings: 4.5,
                        numReviews:10,
                        description: 'High quality product',
                        },
                        {
                            id: "6",
                            name:'Ray ban polaroid',
                            category:'life styles',
                            image:'/images/p6.jpg',
                            price: 2599,
                            countInStock: 10,
                            brand: 'glass',
                            ratings: 4,
                            numReviews:10,
                            description: 'High quality product',
                            },
                            {
                                id: "7",
                                name:'Louis vuitton Sun Glass',
                                category:'life styles',
                                image:'/images/p7.jpg',
                                price: 21899,
                                countInStock: 40,
                                brand: 'glass',
                                ratings: 4.8,
                                numReviews:10,
                                description: 'High quality product',
                                },
                                {
                                    id: "8",
                                    name:'Fastrack Watch',
                                    category:'life styles',
                                    image:'/images/p8.jpg',
                                    price: 2799,
                                    countInStock: 0,
                                    brand: 'Watch',
                                    ratings: 3.7,
                                    numReviews:10,
                                    description: 'High quality product',
                                    },

    ],
};
export default data;